# Generated by Django 5.1 on 2024-08-30 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2024, 9, 2, 2, 13, 12, 783325, tzinfo=datetime.timezone.utc))),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
